[package]
name = "cove-common"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
tracing = { workspace = true }
tonic = { workspace = true }
async-trait = { workspace = true }
