steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/cove-worker:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/cove-worker:${SHORT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - beta
      - run
      - worker-pools
      - deploy
      - ${_WORKER_POOL}
      - --region=${_REGION}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/cove-worker:${SHORT_SHA}
      - --command=cove-worker
      - --scaling=${_SCALING}
      - --update-secrets=COVE_PUSH__APNS_PRIVATE_KEY=${_APNS_SECRET}:latest
      - --update-env-vars=COVE_PUSH__APNS_PRIVATE_KEY_PATH=/tmp/secrets/AuthKey.p8

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/cove-worker:${SHORT_SHA}

substitutions:
  _REGION: us-central1
  _AR_REPO: cove
  _WORKER_POOL: cove-worker
  _SCALING: "1"
  _APNS_SECRET: cove-apns-authkey

options:
  logging: CLOUD_LOGGING_ONLY
