#!/usr/bin/env bash
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${BOLD}${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${BOLD}${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${BOLD}${RED}[✗]${NC} $1"; }
step()  { echo -e "\n${BOLD}--- $1 ---${NC}"; }

# ─── Check / install prerequisites ───────────────────────────────────────────

step "Checking prerequisites"

if ! command -v brew &>/dev/null; then
    err "Homebrew not found. Install it from https://brew.sh"
    exit 1
fi
info "Homebrew found"

if ! command -v rustup &>/dev/null; then
    warn "Rust not found — installing via rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
fi
info "Rust $(rustc --version | awk '{print $2}')"

if ! command -v protoc &>/dev/null; then
    warn "protoc not found — installing via Homebrew"
    brew install protobuf
fi
info "protoc $(protoc --version | awk '{print $2}')"

if ! command -v docker &>/dev/null; then
    warn "Docker not found — installing Docker Desktop via Homebrew"
    brew install --cask docker
    echo ""
    warn "Docker Desktop installed. Open it from Applications and start the engine."
    warn "Then re-run this script."
    exit 1
fi
info "Docker $(docker --version | awk '{print $3}' | tr -d ',')"

if ! docker info &>/dev/null 2>&1; then
    err "Docker engine is not running. Start Docker Desktop, then re-run this script."
    exit 1
fi
info "Docker engine is running"

# ─── Create secrets ──────────────────────────────────────────────────────────

step "Setting up secrets"

SECRETS_DIR="$(cd "$(dirname "$0")/.." && pwd)/secrets"
mkdir -p "$SECRETS_DIR"

if [ ! -f "$SECRETS_DIR/master.key" ]; then
    openssl rand -hex 32 > "$SECRETS_DIR/master.key"
    info "Generated master encryption key at secrets/master.key"
else
    info "Master key already exists"
fi

# ─── Create .env if missing ──────────────────────────────────────────────────

step "Setting up environment"

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
if [ ! -f "$PROJECT_DIR/.env" ]; then
    JWT_SECRET=$(openssl rand -hex 32)

    cat > "$PROJECT_DIR/.env" <<EOF
# Auto-generated by setup.sh — change for production
JWT_SECRET=${JWT_SECRET}
DATABASE_URL=postgresql://postgres:replace-me@db.your-project-ref.supabase.co:5432/postgres
SUPABASE_STORAGE_ENDPOINT=https://your-project-ref.storage.supabase.co/storage/v1/s3
SUPABASE_STORAGE_BUCKET=media
SUPABASE_SECRET_KEY=replace-me
PORT=50051
EOF
    info "Generated .env with random secrets"
else
    info ".env already exists"
fi

# ─── Build Rust binaries ─────────────────────────────────────────────────────

step "Building CoveServer (release mode)"

cd "$PROJECT_DIR"
cargo build --release --workspace 2>&1

info "Build complete"
echo "  Binaries:"
echo "    target/release/cove-server"
echo "    target/release/cove-worker"

# ─── Done ────────────────────────────────────────────────────────────────────

step "Setup complete"

echo ""
echo -e "  ${BOLD}To start with Docker Compose (recommended):${NC}"
echo "    docker compose up -d"
echo ""
echo -e "  ${BOLD}To run locally for development:${NC}"
echo "    # Run the server and worker:"
echo "    cargo run --bin cove-server"
echo "    cargo run --bin cove-worker   # in another terminal"
echo ""
echo "    # Ensure .env has valid SUPABASE_* values before running."
echo ""
echo -e "  ${BOLD}To check logs:${NC}"
echo "    docker compose logs -f cove-api"
echo "    docker compose logs -f cove-worker"
echo ""
echo -e "  ${BOLD}gRPC endpoint:${NC}  localhost:50051 (dev) or :443 (Docker w/ TLS)"
echo -e "  ${BOLD}Metrics:${NC}        http://localhost:9090"
echo ""
